<a class="sponsor-btn" href="https://your-link-here.com" target="_blank">
    ❤️ Sponsor Us
</a>
.sponsor-btn {
    display: inline-block;
    padding: 12px 22px;
    background: linear-gradient(135deg, #ff4d4d, #ff1a75);
    color: white;
    font-size: 18px;
    font-weight: 600;
    border-radius: 8px;
    text-decoration: none;
    transition: 0.25s ease;
    box-shadow: 0 4px 12px rgba(255, 0, 80, 0.4);
}

.sponsor-btn:hover {
    transform: translateY(-3px);
    box-shadow: 0 6px 18px rgba(255, 0, 80, 0.55);
}


github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
thanks_dev: # Replace with a single thanks.dev username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
